# Generated by Django 5.0.4 on 2024-06-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_event_parent_event_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventImage',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
